### ISSUE TITLE
Without Blender ID, checkout fails and gives misleading info

### ISSUE THREAD

**Issue by tonroosendaal** [bartv42/cloudshop#26] opened 2014-09-14 08:47 UTC
Logout, and order cloud, then click on "checkout" (not 'view cart')
The store says "go to the Billing & Shipping section". Which does not exist. 

With some fiddling you can find out how to make an account, but It then takes at least three steps to make an 'ID'. 

At least the text should say prominently "Make a new account ("Blender ID") here" or so.

![screen shot 2014-09-14 at 10 35 07](https://cloud.githubusercontent.com/assets/6818057/4263485/6f65507e-3bea-11e4-85e9-f7d6529d60c5.png)

**Comment by tonroosendaal** [comment] 2014-09-14 08:50
Another problem on same page:

If you try to login with not existing account (or make a typo), no error message is being displayed.

**Comment by bartv42** [comment] 2014-09-14 09:04
Ok, ik kan toch niet slapen dus ik kijk er meteen even naar.

-- 
Bart Veldhuizen

Op 14 september 2014 at 04:50:11, tonroosendaal (notifications@github.com) schreef:

Another problem on same page:

If you try to login with not existing account (or make a typo), no error message is being displayed.

**Comment by bartv42** [comment] 2014-09-14 09:53
Ik heb een fix klaargezet voor allebei je issues. Francesco doet een review.
-- 
Bart Veldhuizen

Op 14 september 2014 at 05:04:32, Bart Veldhuizen (bart.veldhuizen@gmail.com) schreef:

Ok, ik kan toch niet slapen dus ik kijk er meteen even naar.

-- 
Bart Veldhuizen

Op 14 september 2014 at 04:50:11, tonroosendaal (notifications@github.com) schreef:

Another problem on same page:

If you try to login with not existing account (or make a typo), no error message is being displayed.

**Comment by bartv42** [comment] 2014-09-14 10:03
@Francesco: this is a duplicate of #27 and #28, I didn't realise this issue was already here on Github/Waffle

**Closed as completed** 2014-09-15 08:55 UTC
